# Base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# IGDB (Twitch Developer)
igdb.client-id=${IGDB_CLIENT_ID}
igdb.client-secret=${IGDB_CLIENT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true