name: java CI game-comparer

on:
  push:
    branches: 
      - "main"
      - "test-actions"
      - "test-sphinx"
  pull_request:
    branches: 
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: gfe
          MYSQL_DATABASE: mi_app_db
        ports:
          - 3306:3306
                
          #Verificación de que MYSQL funciona correctamente
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
            
      - name: BD
        run: mvn -B package --file game-comparer/pom.xml
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/mi_app_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: gfe
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
  docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test-sphinx')

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Sphinx
        run: pip install sphinx sphinx-rtd-theme myst-parser

      - name: Debug estructura
        run: |
          echo "_________ Raiz del repo _________"
          ls -la
          echo "_________ Buscar conf.py _________"
          find . -name "conf.py"

      - name: Build HTML
        run: sphinx-build game-comparer/docs/ game-comparer/docs/_build/html

      - name: Verificar output
        run: |
          echo "_________ Contenido _build _________"
          ls -la game-comparer/docs/_build/html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./game-comparer/docs/_build/html
          destination_dir: sphinx
          keep_files: true

  doxygen:
    runs-on: ubuntu-latest
    needs: docs
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test-sphinx')

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen
        run: doxygen game-comparer/Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./game-comparer/doxygen-output/html
          destination_dir: doxygen
          keep_files: true